simplesocial/groups/urls.py
#urls.py for groups app
from django.urls import path
from . inport views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('post/in/<slug:slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>/',views.LeaveGroup.as_view(),name='leave'),
]

simplesocial/posts/urls.py
#post urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='all'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<pk>',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete')
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('text/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

simplesocial/groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify #it removes spaces from a string and add - in place so that we can use that string as url
import misaka # it is used for link embadding with string
from django.contrib.auth import get_user_model # it retyurns user model that is a tive in this project. which allows to call things off of current user session.

User = get_user_model()
# Create your models here.

from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember') #one user can be a member of many groups as well as one group can have many users i.e. manytomany relationship

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta():
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta():
        unique_together = ('user','group')

simplesocial/groups/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from groups.models import Group,GroupMember
# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**keargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.Create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Already a member!')
        else:
            messages.success(self.request,'You are not a member!')

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**keargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        try:
            membership = models.GroupMember.object.filter(user=self.request.user, group__slug=self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry, you are not part of this group!')
        else:
            membership.delete()
            messages.success(self.request,"You have successfully left the group")
            return super().get(request,*args,**kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      {% block pregroup %}{% endblock %}
      {% block groupcontent %}{% endblock %}
      {% block postgroup %}{% endblock %}
    </div>
  </div>
{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% ectends 'groups/group_base.html' %}
{% block pregroup %}
  <h1>{{ group.name }}</h1>
  <h2>Member Count: {{ geoup.members.count }}</h2>

  <div class="content">
    {% if user in group.members.all %}
      <a class="btn btn-warning" href="{% url 'groups:leave' slug=group.slug %}">
        <span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
    {% else %}
      <a class="btn btn-success" href="{% url 'groups:join' slug=group.slug %}">
        <span class='glyphicon glyphicon-ok-circle'></span>Join</a>
    {% endif %}
  </div>
{% endblock %}

{% block groupcontent %}
  <div class="col-md-8">
    {% if group.post.count == 0 %}
      <h2>No post to display in this group!</h2>
    {% else %}
      {% for post in group.post.all %}
        {% include 'posts/_post.html' %}
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}
{% block groupcontent %}
  <h4>Creatye new grup!</h4>

  <form action="{% url 'groups:create' %}" method="POST" id='groupForm'>
    {% csrf_token %}
    {% bootstrat_form form %}
    <input type="submit" class="btn btn-primary" value="Create">
  </form>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2>Welcome Back! <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a></h2>
      {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
      <a class="btn btn-default" href="{% url 'groups:create' %}">
        <span class="glyphicon glyphicon-plus-sign">Create New Group</span></a>
    {% endif %}
  </div>
{% endblock %}

{% block groupcontent %}
  <div class="col-md-8">
    <div class="listgroup">
      {% for group in object_list %}
        <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}">
          <h3 class='title list-group-item-heading'>{{ group.name }}</h3>
          <div class="list-group-item-text container-fluid">
            {{ group.description_html|safe }}
            <div class="row">
              <div class="col-md-4">
                <span class="badge">{{ group.members.count }}</span>
                member{{ group.members.count|pluralize }}
              </div>
              <div class="col-md-4">
                <span class='badge'>{{ group.posts.count }}</span>
                post{{ group.posts.count|pluralize }}
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}